server:
  port: 8085
spring:
  application:
    name: "gestion-produit"
  datasource:
    url: "jdbc:mysql://localhost:3306/bd_gestion_produit?serverTimezone=Africa/Douala&createDatabaseIfNotExist=true"
    username: "root"
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect




